site_name: Tippler's Log
site_url: "https://yhf216.github.io"
theme:
  name: material
  language: zh

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: 切换至深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式

copyright: Copyright © 2026 Tippler. All Rights Reserved.