site_name: Tippler's Log
site_url: "https://yhf216.github.io"
theme:
  name: material
  language: zh

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

copyright: Copyright © 2026 Tippler. All Rights Reserved.